CREATE DATABASE QLNS
GO
USE QLNS

CREATE TABLE CHUCNANG (
	idCN int primary key IDENTITY(1,1),
	MaCN AS CAST('CN' + right('000' + CAST(idCN as varchar(3)), 3) as char(6))persisted,
	TenCN NVARCHAR(MAX) NOT NULL, 
	MoTa NVARCHAR(MAX),
);

CREATE TABLE LOAINGUOIDUNG (
	idLND int IDENTITY(1,1) primary key,
	MaLND AS CAST('LND' + right('000' + CAST(idLND as varchar(3)), 3) AS CHAR(6)) persisted ,
	TenLND NVARCHAR(MAX) NOT NULL,
	MoTa NVARCHAR(MAX),
);

CREATE TABLE PHANQUYEN (
	idLND INT FOREIGN KEY REFERENCES LOAINGUOIDUNG on delete cascade,
    idCN INT FOREIGN KEY REFERENCES CHUCNANG on delete cascade,
    PRIMARY KEY (idLND, idCN),
);

CREATE TABLE NHANVIEN (
	idNV INT IDENTITY(1,1) PRIMARY KEY,
	MaNV AS CAST('NV'+ RIGHT('000000' + CAST(idNV AS VARCHAR(3)), 3) AS CHAR(6)) PERSISTED,
	TenNV NVARCHAR(MAX) NOT NULL,
	NgaySinh DATETIME NOT NULL, 
	DiaChi NVARCHAR(MAX),
	SDT VARCHAR(10),
	NgayVL Datetime NOT NULL, 
	ChucVu NVARCHAR(MAX) NOT NULL,
	TinhTrang BIT NOT NULL,
	GhiChu NVARCHAR(MAX),
);

CREATE TABLE NGUOIDUNG (
	idND INT IDENTITY(1,1) PRIMARY KEY,
	MaND AS CAST('ND'+ RIGHT('000000' + CAST(idND AS VARCHAR(3)), 3) AS CHAR(6)) PERSISTED,
	TenDN VARCHAR(MAX) UNIQUE NOT NULL,
	MatKhau VARCHAR(MAX) NOT NULL,
	NgayTao DATETIME,
	TinhTrang BIT NOT NULL,
	idNV INT REFERENCES NHANVIEN ON DELETE CASCADE NOT NULL,
    idLND INT REFERENCES LOAINGUOIDUNG on delete cascade NOT NULL,
);

CREATE TABLE LOAIKHACHHANG (
	idLKH INT IDENTITY(1,1) PRIMARY KEY,
	MaLKH AS CAST('LKH'+ RIGHT('000' + CAST(idLKH AS VARCHAR(3)), 3) AS CHAR(6))PERSISTED,
	TenLKH NVARCHAR(MAX) NOT NULL,
	MoTa NVARCHAR(MAX),
	DiemTichLuyToiThieu INT NOT NULL,
);

CREATE TABLE KHACHHANG (
	idKH int IDENTITY(1,1) PRIMARY KEY,
	MaKH AS CAST('KH'+ RIGHT('000' + CAST(idKH AS VARCHAR(3)), 3) AS CHAR(6))PERSISTED,
	TenKH NVARCHAR(MAX) NOT NULL,
	NgaySinh DATETIME,
	DiaChi NVARCHAR(MAX),
	SDT VARCHAR(10),
	NgayTG DATETIME NOT NULL, 
	DiemTichLuy INT NOT NULL,
    idLKH INT REFERENCES LOAIKHACHHANG on delete cascade NOT NULL,
);

CREATE TABLE DANHMUC (
	idDM int IDENTITY(1,1)  primary key,
	MaDM As Cast('DM' + right('000' + CAST(idDM as varchar(3)), 3) as char(6)) persisted,  
	TenDM NVARCHAR(MAX) NOT NULL,
	MoTa NVARCHAR(MAX),
);

CREATE TABLE SANPHAM (
	idSP INT IDENTITY(1,1) PRIMARY KEY,
	MaSP AS cast('TTSP'+ right('000' + CAST(idSP AS VARCHAR(3)), 3) as char(6)) PERSISTED,
	TenSP NVARCHAR(MAX) NOT NULL,
	MoTa NVARCHAR(MAX),
	GhiChu NVARCHAR(MAX),
	idDM int references DANHMUC NOT NULL,
);

CREATE TABLE NHAPHANG (
	idNH INT IDENTITY(1,1) PRIMARY KEY,
	MaNH AS CAST('NH'+ RIGHT('000000' + CAST(idNH AS VARCHAR(10)), 5) AS CHAR(6)) PERSISTED,
	NgayNhap DATETIME NOT NULL,
	ThanhTien MONEY NOT NULL,
	GhiChu NVARCHAR(MAX),
	idNV INT REFERENCES NHANVIEN NOT NULL,
);

CREATE TABLE CTSP (
	idCTSP int IDENTITY(1,1) primary key,
	MaCTSP AS CAST('SP'+ RIGHT('000000' + CAST(idCTSP AS VARCHAR(10)), 5) AS CHAR(6)) PERSISTED,
	NgayNhap DATETIME NOT NULL, 
	DonGiaNhap MONEY NOT NULL,
	SoLuongNhap SMALLINT NOT NULL,
	SoLuongLoi SMALLINT NOT NULL,
	DonGiaXuat MONEY NOT NULL,
	DaBan SMALLINT NOT NULL,
	SLConLai SMALLINT NOT NULL,
	GhiChu NVARCHAR(MAX),
	idSP INT REFERENCES SANPHAM NOT NULL,
	idNH INT REFERENCES NHAPHANG NOT NULL,
);

CREATE TABLE KHUYENMAI (
	idKM INT IDENTITY(1,1) PRIMARY KEY,
	MaKM AS CAST('KM'+ RIGHT('000' + CAST(idKM AS VARCHAR(3)), 3) AS CHAR(6)) PERSISTED,
	TenKM NVARCHAR(MAX) NOT NULL,
	MoTa NVARCHAR(MAX),
	idLKH INT REFERENCES LOAIKHACHHANG, 
	NgayBD DATETIME NOT NULL,
	NgayKT DATETIME NOT NULL,
	GiamGia NUMERIC(3,2) NOT NULL,
	idNV INT REFERENCES NHANVIEN NOT NULL,
);

CREATE TABLE HOADON (
	idHD int IDENTITY(1,1) primary key,
	SoHD AS CAST('HD'+ RIGHT('000000' + CAST(idHD AS VARCHAR(10)), 5) AS CHAR(6)) PERSISTED,
	NgayHD DATETIME NOT NULL,
	GiamGia MONEY NOT NULL,
	ThanhTien MONEY NOT NULL,
	GhiChu NVARCHAR(MAX),
	idKH INT REFERENCES KHACHHANG,
	idKM INT REFERENCES KHUYENMAI,
	idNV INT REFERENCES NHANVIEN NOT NULL,
);

CREATE TABLE CTHD (
	idHD INT FOREIGN KEY REFERENCES HOADON on delete cascade,
    idCTSP INT FOREIGN KEY REFERENCES CTSP on delete cascade,
	SoLuong INT NOT NULL,
	DonGia MONEY NOT NULL,
	GiamGia MONEY,
	ThanhTien MONEY NOT NULL,
	GhiChu NVARCHAR(MAX),
    PRIMARY KEY (idHD, idCTSP),
);
