//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTSP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CTSP()
        {
            this.CTHDs = new HashSet<CTHD>();
        }
    
        public int idCTSP { get; set; }
        public string MaCTSP { get; set; }
        public System.DateTime NgayNhap { get; set; }
        public decimal DonGiaNhap { get; set; }
        public short SoLuongNhap { get; set; }
        public short SoLuongLoi { get; set; }
        public decimal DonGiaXuat { get; set; }
        public short DaBan { get; set; }
        public short SLConLai { get; set; }
        public string GhiChu { get; set; }
        public int idSP { get; set; }
        public int idNH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD> CTHDs { get; set; }
        public virtual NHAPHANG NHAPHANG { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
