//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADON()
        {
            this.CTHDs = new HashSet<CTHD>();
        }
    
        public int idHD { get; set; }
        public string SoHD { get; set; }
        public System.DateTime NgayHD { get; set; }
        public decimal GiamGia { get; set; }
        public decimal ThanhTien { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> idLKH { get; set; }
        public Nullable<int> idKH { get; set; }
        public Nullable<int> idKM { get; set; }
        public int idND { get; set; }
        public int idPT { get; set; }
        public Nullable<int> SLSP { get; set; }
        public Nullable<decimal> ThanhToan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD> CTHDs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual KHUYENMAI KHUYENMAI { get; set; }
        public virtual LOAIKHACHHANG LOAIKHACHHANG { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
        public virtual PTTHANHTOAN PTTHANHTOAN { get; set; }
    }
}
