//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAMLOI
    {
        public int idSPL { get; set; }
        public string MaSPL { get; set; }
        public int idCTSP { get; set; }
        public short SoLuongLoi { get; set; }
        public System.DateTime NgayLoi { get; set; }
        public string ChiTietLoi { get; set; }
        public string GhiChu { get; set; }
        public int idND { get; set; }
    
        public virtual CTSP CTSP { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
    }
}
